FROM python:3.10-slim

WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy exporter script
COPY 3.prometheus_exporter.py prometheus_exporter.py

# Expose metrics port
EXPOSE 8000

# Run exporter
CMD ["python", "prometheus_exporter.py"]